### ISSUE TITLE
Martell player's turn skipped after playing Doran Martell in defense 

### ISSUE THREAD

**Issue by AlecEJones** [Longwelwind/swords-and-ravens#676] opened 2020-05-29 02:05 UTC
Hi there, reporting a bug from an edge-case scenario we encountered.

Tyrell - IT track position 2
Martell - IT track position 3
Stark - IT track position 4

1) Tyrell's turn - attacks Martell. Martell plays 'Doran' in defense, moves Tyrell to bottom position of IT track.
2) Martell moves to position 2, Stark moves to position 3.

Next turn is Stark, skipping over Martell (who had attack tokens on the board).

My guess is that the algorithm should check to see if the player on the existing position has changed before moving to the next position on the track.

**Comment by gereon77** [comment] 2020-05-29 03:58
It’s by design. See #616 

Q: Is it possible for a player’s turn be ‘skipped’ if the “Doran Martell” house card moves his token to the last position of the Iron Throne track?

A: Yes, it is possible for a House’s turn to be skipped after the resolution of Doran’s text ability.

The turn order of the Iron Throne track is always followed exactly as it appears; the “1” position goes first, followed by the “2” position, followed by position “3”, etc. It is the position on the track itself that determines the current player, regardless of which Houses have taken their turn.

For example, if the current player is in position “5” but is then moved to the end of the track (position “6”) as a result of Doran’ text ability, he would also be the next player, because position “6” always comes after position “5” no matter which Houses were occupying those slots previously. In the same way, the player whose House had previously been in position “6” (and is now in position “5”) must wait through another cycle of turns before resolving his next order.

**Closed** 2020-06-01 01:59 UTC
