### ISSUE TITLE
Player count on Games page can go higher than the limit

### ISSUE THREAD

**Issue by Longwelwind** [Longwelwind/swords-and-ravens#553] opened 2020-04-18 06:45 UTC
![image](https://user-images.githubusercontent.com/9724878/79630368-f1a96a00-8150-11ea-9386-bbd31d704543.png)

**Comment by gereon77** [comment] 2020-04-22 13:33
@Longwelwind: I found the root cause of the problem and it is fixed by #555 already. Maybe due to that you want to merge it to master directly?

It can be reproduced by following steps:

1. Create a 4p game.
2. Fill all selectable houses
3. Let a 5th player join
4. As everyone can change the settings the 5th player can change it to a 5 player mode on his own which in fact just bypasses the UI restriction on his machine. The game mode itself stays on 4p.
5. But he now is allowed to send `choose-house` for a non participating house which results in the bug described here


But maybe in addition to #555 we want to add a check in `LobbyGameState.onClientMessage` if the chosen house is available in the current game setting to avoid spoofing the package?

**Closed** 2020-05-09 18:48 UTC
Labels: type:bug
